Controllers/PedidosController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InduccionSemana4.Models;
using InduccionSemana4.Models.Contexto;
using MediatR;
using InduccionSemana4.Models.Consultas.ReadPedido;
using InduccionSemana4.Models.Comandos.CommandPedido;
using InduccionSemana4.Models.Consultas.ReadCliente;
using InduccionSemana4.Models.Consultas.ReadVendedor;
using Microsoft.Data.SqlClient;
using Dapper;
using InduccionSemana4.Models.Consultas.ReadProducto;

namespace InduccionSemana4.Controllers
{
    public class PedidosController : Controller
    {
        private readonly IMediator _mediator;

        public PedidosController(IMediator mediator)
        {
            _mediator = mediator;
        }

        // GET: Pedidoes
        public async Task<ActionResult> Index()
        {
            return View(await _mediator.Send(new PedidoCrudSelect.SelectProducto()));
        }

        // GET: Pedidoes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendedor = await _mediator.Send(new PedidoCrudSelectGetById.SelectIdPedido { Id = id });
            if (vendedor == null)
            {
                return NotFound();
            }

            return View(vendedor);
        }

        // GET: Pedidoes/Create
        public async Task<ActionResult> Create(int ProductoId)
        {
            var vendedores = await _mediator.Send(new VendedorCrudSelect.SelectVendedor());
            List<SelectListItem> clientesSLI = new List<SelectListItem>();
            foreach (var item in vendedores)
            {
                SelectListItem listItem = new SelectListItem { Text = item.Id + " " + item.TitularNegocio, Value = item.Id.ToString() };
                clientesSLI.Add(listItem);
            }
            ViewBag.vendedores = clientesSLI;

            var mediatorProducto = await _mediator.Send(new ProductoCrudSelectById.SelectIdProducto() { Id = ProductoId });
            ViewBag.productoPrecio = mediatorProducto.Precio.ToString();
            Pedido pedido = new Pedido();
            pedido.ProductoId = ProductoId;



            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClavePedido,PrecioTotal,Cantidad,ClienteId,ProductoId")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {


                var numReg = await _mediator.Send(new PedidoCrudInsert.InsertProducto { Pedido = pedido });
                return RedirectToAction(nameof(Index));
            }
            return BadRequest("Error al guardar");
        }

        // GET: Pedidoes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _mediator.Send(new PedidoCrudSelectGetById.SelectIdPedido() { Id = id });
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedidoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClavePedido,PrecioTotal,Cantidad,ClienteId,ProductoId")] Pedido pedido)
        {
            if (id != pedido.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var numReg = await _mediator.Send(new PedidoCrudUpdate.UpdatePedido { Pedido = pedido });
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound("Error al Actualizar");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedidoes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _mediator.Send(new PedidoCrudSelectGetById.SelectIdPedido() { Id = id });
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedidoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var pedido = await _mediator.Send(new PedidoCrudSelectGetById.SelectIdPedido() { Id = id });
                    var numReg = await _mediator.Send(new PedidoCrudDelete.DeletePedido() { Pedido = pedido });
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound("Error al Actualizar");
                }

            }
            return RedirectToAction(nameof(Index));
        }

        //private bool PedidoExists(int id)
        //{
        //    return _context.Pedidos.Any(e => e.Id == id);
        //}
    }
}

Controllers/ProductoController.cs
using Dapper;
using InduccionSemana4.Models;
using InduccionSemana4.Models.Comandos.CommandProducto;
using InduccionSemana4.Models.Consultas.ReadProducto;
using InduccionSemana4.Models.Consultas.ReadVendedor;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace InduccionSemana4.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IMediator Mediator;

        public ProductoController(IMediator mediator)
        {
            Mediator = mediator;
        }

        // GET: Producto
        public async Task<ActionResult<List<Producto>>> Index()
        {
            var a = await Mediator.Send(new ProductoCrudSelect.SelectProducto());
            return View(a);
        }

        // Buscar por filtros
        public IActionResult Menu(string searchString)
        {
            string sqlRest = "SELECT * FROM Productos";
            using (var connection = new SqlConnection("Data Source= MEX-J6TNMG3\\SQLEXPRESS; Initial Catalog=RestaurantOnline; Trusted_Connection=True; MultipleActiveResultSets=true"))
            {
                var res = connection.Query<Producto>(sqlRest).AsQueryable();
                if (!String.IsNullOrEmpty(searchString))
                {
                    res = res.Where(a => a.Categoria.Contains(searchString));
                }
                ViewData["CurrentFilter"] = searchString;
                return View(res.ToList());
            }
        }


        // get: Producto/details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await Mediator.Send(new ProductoCrudSelectById.SelectIdProducto() { Id = id });
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create para insertar un pedido
        public async Task<ActionResult> Create2(Pedido pedido)
        {
            var vendedores = await Mediator.Send(new VendedorCrudSelect.SelectVendedor());
            List<SelectListItem> clientesSLI = new List<SelectListItem>();
            foreach (var item in vendedores)
            {
                SelectListItem listItem = new SelectListItem { Text = item.Id + " " + item.NombreNegocio, Value = item.Id.ToString() };
                clientesSLI.Add(listItem);
            }
            ViewBag.vendedores = clientesSLI;
            return View();
        }


        // GET: Producto/Create
        public async Task<ActionResult> Create()
        {
            var vendedores = await Mediator.Send(new VendedorCrudSelect.SelectVendedor());
            List<SelectListItem> clientesSLI = new List<SelectListItem>();
            foreach (var item in vendedores)
            {
                SelectListItem listItem = new SelectListItem { Text = item.Id + " " + item.NombreNegocio, Value = item.Id.ToString() };
                clientesSLI.Add(listItem);
            }
            ViewBag.vendedores = clientesSLI;
            return View();
        }

        // POST: Producto/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClaveProducto,NombreProducto,Stock,Precio,Descripcion,Categoria,VendedorId")] Producto producto)
        {


            if (ModelState.IsValid)
            {
                await Mediator.Send(new ProductoCrudInsert.InsertProducto() { Producto = producto });
                return RedirectToAction(nameof(Index));
            }
            return BadRequest("Errro al guardar");

        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendedores = await Mediator.Send(new VendedorCrudSelect.SelectVendedor());
            List<SelectListItem> clientesSLI = new List<SelectListItem>();
            foreach (var item in vendedores)
            {
                SelectListItem listItem = new SelectListItem { Text = item.Id + " " + item.NombreNegocio, Value = item.Id.ToString() };
                clientesSLI.Add(listItem);
            }
            ViewBag.vendedores = clientesSLI;

            var producto = await Mediator.Send(new ProductoCrudSelectById.SelectIdProducto() { Id = id });
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClaveProducto,NombreProducto,Stock,Precio,Descripcion,Categoria,VendedorId")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var numReg = await Mediator.Send(new ProductoCrudUpdate.UpdateProducto { Producto = producto });
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound("Error al Actualizar");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producto = await Mediator.Send(new ProductoCrudSelectById.SelectIdProducto() { Id = id });
            if (producto == null) return NotFound();

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var p = await Mediator.Send(new ProductoCrudSelectById.SelectIdProducto() { Id = id });
                    var produc = await Mediator.Send(new ProductoCrudDelete.DeleteProducto() { producto = p });
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound("Error al Actualizar");
                }

            }
            return RedirectToAction(nameof(Index));
        }


    }
}


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InduccionSemana4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InduccionSemana4.styles.css" asp-append-version="true" />

    <!-- MDBootstrap V5 -->
	<link rel="stylesheet" href="~/RESTAURANT-main/css/mdb.min.css">

	<!-- Font Awesome V5.15.1 -->
	<link rel="stylesheet" href="~/RESTAURANT-main/css/all.css">

	<!-- Sweet Alert V10.13.0 -->
	<script src="~/RESTAURANT-main/js/sweetalert2.js" ></script>

	<!-- General Styles -->
	<link rel="stylesheet" href="~/RESTAURANT-main/css/style.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restaurant Online</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="header-navbar full-box poppins-regular font-weight-bold">
                    <ul class="list-unstyled full-box">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="full-box" ></span></a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendedor" asp-action="Menu">Menu<span class="full-box" ></span></a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendedor" asp-action="Index">Vendedor<span class="full-box" ></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Menu">Cliente<span class="full-box" ></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InduccionSemana4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/RESTAURANT-main/js/mdb.min.js" ></script>

	<!-- General scripts -->
	<script src="~/RESTAURANT-main/js/main.js" ></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>